import { useEffect, useState } from "react";
import { generateReport, getAllReports, deleteReport } from "../api/api";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function DailyReport() {
    const [date, setDate] = useState("");
    const [reports, setReports] = useState([]);
    const [show, setShow] = useState(true);
    const [loading, setLoading] = useState(false);

    const load = async () => {
        setLoading(true);
        const res = await getAllReports();
        setReports(res.reports);
        setLoading(false);
    };

    useEffect(() => {
        load();
    }, []);

    const handleGenerate = async () => {
        if (!date) {
            showNotification("Please select a date", "error");
            return;
        }
        setLoading(true);
        await generateReport({ date });
        await load();
        showNotification("Report generated successfully!", "success");
        setLoading(false);
    };

    const copyReport = (r) => {
        const text = r.records.map(rec =>
            `${rec.plateNumber} | ${rec.entryTime} | ${rec.exitTime} | ${rec.duration}h | ${rec.amountPaid} RWF`
        ).join("\n");
        
        navigator.clipboard.writeText(text);
        showNotification("Report copied to clipboard!", "success");
    };

    const downloadPDF = (r) => {
        const doc = new jsPDF();
        
        doc.setFillColor(147, 51, 234);
        doc.rect(0, 0, 210, 40, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(20);
        doc.text("PSSMS DAILY REPORT", 20, 25);
        
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);
        doc.text(`Date: ${r.date}`, 20, 55);
        
        autoTable(doc, {
            startY: 65,
            head: [['Plate Number', 'Entry Time', 'Exit Time', 'Duration', 'Amount (RWF)']],
            body: r.records.map(rec => [
                rec.plateNumber,
                rec.entryTime,
                rec.exitTime,
                `${rec.duration}h`,
                rec.amountPaid
            ]),
            foot: [['', '', '', 'Total:', r.total]],
            headStyles: { fillColor: [147, 51, 234] },
            footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' }
        });
        
        doc.save(`report-${r.date}.pdf`);
        showNotification("PDF downloaded successfully!", "success");
    };

    const downloadReport = (r) => {
        const content = `PSSMS DAILY REPORT - ${r.date}
        
${'='.repeat(60)}
Plate | Entry | Exit | Duration | Amount
${'-'.repeat(60)}
${r.records.map(rec => 
    `${rec.plateNumber.padEnd(10)} | ${rec.entryTime.padEnd(15)} | ${rec.exitTime.padEnd(15)} | ${rec.duration}h`.padEnd(8) + ` | ${rec.amountPaid} RWF`
).join('\n')}
${'='.repeat(60)}
TOTAL: ${r.total} RWF

Generated by PSSMS Parking System`;

        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `report-${r.date}.txt`;
        a.click();
        URL.revokeObjectURL(url);
        showNotification("Report downloaded successfully!", "success");
    };

    const handleDelete = async (id) => {
        if (!window.confirm("Are you sure you want to delete this report?")) return;
        
        setLoading(true);
        await deleteReport(id);
        await load();
        showNotification("Report deleted successfully!", "error");
        setLoading(false);
    };

    const showNotification = (message, type) => {
        const notification = document.createElement('div');
        notification.className = `fixed top-4 right-4 z-50 px-6 py-3 rounded-xl shadow-2xl animate-slide-in flex items-center gap-2 ${
            type === 'success' ? 'bg-gradient-to-r from-green-500 to-emerald-600' : 'bg-gradient-to-r from-red-500 to-pink-600'
        } text-white`;
        notification.innerHTML = `
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="${
                    type === 'success' ? 'M5 13l4 4L19 7' : 'M6 18L18 6M6 6l12 12'
                }"></path>
            </svg>
            <span>${message}</span>
        `;
        document.body.appendChild(notification);
        setTimeout(() => notification.remove(), 3000);
    };

    return (
        <div className="space-y-6 animate-fade-in-up">
            {/* Header */}
            <div>
                <h1 className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
                    Daily Reports
                </h1>
                <p className="text-gray-500 mt-1">Generate and manage daily parking reports</p>
            </div>

            {/* Report Generator */}
            <div className="bg-gradient-to-br from-purple-600 to-pink-600 rounded-2xl p-6 shadow-xl text-white">
                <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                    <span className="text-2xl">📊</span>
                    Generate New Report
                </h2>
                <div className="flex flex-col md:flex-row gap-4">
                    <div className="flex-1">
                        <label className="block text-sm font-medium mb-2">Select Date</label>
                        <input
                            type="date"
                            className="w-full px-4 py-3 rounded-xl text-gray-800 focus:outline-none focus:ring-2 focus:ring-white/50"
                            onChange={(e) => setDate(e.target.value)}
                        />
                    </div>
                    <div className="flex items-end gap-3">
                        <button
                            onClick={handleGenerate}
                            disabled={loading}
                            className="bg-white text-purple-600 px-6 py-3 rounded-xl font-semibold hover:shadow-lg hover:scale-105 transition-all duration-300 disabled:opacity-50 flex items-center gap-2"
                        >
                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                            </svg>
                            Generate Report
                        </button>
                        <button
                            onClick={() => setShow(!show)}
                            className="bg-white/20 backdrop-blur-sm px-6 py-3 rounded-xl font-semibold hover:bg-white/30 transition-all duration-300 flex items-center gap-2"
                        >
                            {show ? (
                                <>
                                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
                                    </svg>
                                    Hide Reports
                                </>
                            ) : (
                                <>
                                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                    </svg>
                                    Show Reports
                                </>
                            )}
                        </button>
                    </div>
                </div>
            </div>

            {/* Reports List */}
            {show && (
                <div className="space-y-6">
                    {loading && reports.length === 0 ? (
                        <div className="flex justify-center items-center h-64">
                            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-500"></div>
                        </div>
                    ) : reports.length === 0 ? (
                        <div className="text-center py-12 bg-gray-50 rounded-2xl">
                            <div className="text-6xl mb-4">📊</div>
                            <p className="text-gray-500 text-lg">No reports available</p>
                            <p className="text-gray-400">Generate your first report using the form above</p>
                        </div>
                    ) : (
                        reports.map((r, index) => (
                            <div
                                key={r._id}
                                className="bg-white rounded-2xl shadow-xl overflow-hidden hover:shadow-2xl transition-all duration-300 animate-fade-in-up"
                                style={{ animationDelay: `${index * 0.1}s` }}
                            >
                                <div className="bg-gradient-to-r from-purple-500 to-pink-500 p-4 text-white">
                                    <div className="flex justify-between items-center flex-wrap gap-3">
                                        <div className="flex items-center gap-3">
                                            <span className="text-2xl">📅</span>
                                            <h3 className="text-xl font-bold">{r.date}</h3>
                                        </div>
                                        <div className="flex gap-2">
                                            <button
                                                onClick={() => copyReport(r)}
                                                className="bg-white/20 hover:bg-white/30 px-4 py-2 rounded-lg transition-all duration-300 flex items-center gap-2"
                                            >
                                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
                                                </svg>
                                                Copy
                                            </button>
                                            <button
                                                onClick={() => downloadPDF(r)}
                                                className="bg-white/20 hover:bg-white/30 px-4 py-2 rounded-lg transition-all duration-300 flex items-center gap-2"
                                            >
                                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                                </svg>
                                                PDF
                                            </button>
                                            <button
                                                onClick={() => downloadReport(r)}
                                                className="bg-white/20 hover:bg-white/30 px-4 py-2 rounded-lg transition-all duration-300 flex items-center gap-2"
                                            >
                                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                                                </svg>
                                                TXT
                                            </button>
                                            <button
                                                onClick={() => handleDelete(r._id)}
                                                className="bg-red-500/20 hover:bg-red-500/30 px-4 py-2 rounded-lg transition-all duration-300 flex items-center gap-2"
                                            >
                                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                </svg>
                                                Delete
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                
                                <div className="overflow-x-auto">
                                    <table className="w-full">
                                        <thead className="bg-gray-50">
                                            <tr>
                                                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">Plate</th>
                                                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">Entry</th>
                                                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">Exit</th>
                                                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">Duration</th>
                                                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {r.records.map((rec, i) => (
                                                <tr key={i} className="border-b border-gray-100 hover:bg-gray-50 transition-colors">
                                                    <td className="px-4 py-3 font-medium">{rec.plateNumber}</td>
                                                    <td className="px-4 py-3 text-sm text-gray-600">{rec.entryTime}</td>
                                                    <td className="px-4 py-3 text-sm text-gray-600">{rec.exitTime}</td>
                                                    <td className="px-4 py-3">{rec.duration}h</td>
                                                    <td className="px-4 py-3 font-semibold text-green-600">{rec.amountPaid} RWF</td>
                                                </tr>
                                            ))}
                                        </tbody>
                                        <tfoot className="bg-gray-50">
                                            <tr>
                                                <td colSpan="4" className="px-4 py-3 text-right font-bold">Total:</td>
                                                <td className="px-4 py-3 font-bold text-purple-600">{r.total} RWF</td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        ))
                    )}
                </div>
            )}
        </div>
    );
}