import { useEffect, useState } from "react";
import { generateReport, getAllReports, deleteReport } from "../api/api";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import Header from "../components/Header";

export default function DailyReport() {
    const [date, setDate] = useState("");
    const [reports, setReports] = useState([]);
    const [show, setShow] = useState(true);
    const [loading, setLoading] = useState(false);

    const load = async () => {
        setLoading(true);
        const res = await getAllReports();
        setReports(res.reports);
        setLoading(false);
    };

    useEffect(() => {
        load();
    }, []);

    const handleGenerate = async () => {
        if (!date) {
            showNotification("Please select a date", "error");
            return;
        }
        setLoading(true);
        await generateReport(date);
        await load();
        showNotification("Report generated successfully!", "success");
        setLoading(false);
    };

    const copyReport = (r) => {
        const text = r.records.map(rec =>
            `${rec.plateNumber} | ${rec.entryTime} | ${rec.exitTime} | ${rec.duration}h | ${rec.amountPaid} RWF`
        ).join("\n");
        
        navigator.clipboard.writeText(text);
        showNotification("Report copied to clipboard!", "success");
    };

    const downloadPDF = (r) => {
        const doc = new jsPDF();
        
        // Header
        doc.setFillColor(22, 163, 74);
        doc.rect(0, 0, 210, 45, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.text("Parking Space Sales Management System", 20, 25);
        doc.setFontSize(12);
        doc.text("Daily Operations Report", 20, 35);
        
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);
        doc.text(`Date: ${r.date}`, 20, 60);
        
        autoTable(doc, {
            startY: 70,
            head: [['Plate Number', 'Entry Time', 'Exit Time', 'Duration', 'Amount (RWF)']],
            body: r.records.map(rec => [
                rec.plateNumber,
                rec.entryTime,
                rec.exitTime,
                `${rec.duration}h`,
                rec.amountPaid
            ]),
            foot: [['', '', '', 'Total:', r.total]],
            headStyles: { fillColor: [22, 163, 74] },
            footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' }
        });
        
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text("Generated by Parking Space Sales Management System", 20, doc.lastAutoTable.finalY + 20);
        doc.save(`eco-report-${r.date}.pdf`);
        showNotification("PDF downloaded successfully!", "success");
    };

    const downloadReport = (r) => {
        const content = `PARKING SPACE SALES MANAGEMENT SYSTEM - DAILY REPORT
${'='.repeat(60)}
Date: ${r.date}
Generated: ${new Date().toLocaleString()}
${'='.repeat(60)}

PLATE NUMBER     | ENTRY TIME        | EXIT TIME         | DURATION | AMOUNT
${'-'.repeat(80)}
${r.records.map(rec => 
    `${rec.plateNumber.padEnd(16)} | ${rec.entryTime.padEnd(18)} | ${rec.exitTime.padEnd(18)} | ${rec.duration}h`.padEnd(9) + ` | ${rec.amountPaid} RWF`
).join('\n')}
${'='.repeat(80)}
TOTAL AMOUNT: ${r.total} RWF
${'='.repeat(80)}

🌿 Thank you for choosing Parking Space Sales Management System!
   This is a carbon-neutral facility.`;

        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `eco-report-${r.date}.txt`;
        a.click();
        URL.revokeObjectURL(url);
        showNotification("Report downloaded successfully!", "success");
    };

    const handleDelete = async (id) => {
        if (!window.confirm("Are you sure you want to delete this report?")) return;
        
        setLoading(true);
        await deleteReport(id);
        await load();
        showNotification("Report deleted successfully!", "success");
        setLoading(false);
    };

    const showNotification = (message, type) => {
        const notification = document.createElement('div');
        notification.className = `fixed top-20 right-4 z-50 px-6 py-3 rounded-xl shadow-2xl animate-slide-in flex items-center gap-2 ${
            type === 'success' ? 'bg-gradient-to-r from-[#16A34A] to-[#15803D]' : 'bg-gradient-to-r from-red-500 to-red-600'
        } text-white`;
        notification.innerHTML = `
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="${
                    type === 'success' ? 'M5 13l4 4L19 7' : 'M6 18L18 6M6 6l12 12'
                }"></path>
            </svg>
            <span>${message}</span>
        `;
        document.body.appendChild(notification);
        setTimeout(() => notification.remove(), 3000);
    };

    const headerActions = (
        <button
            onClick={() => setShow(!show)}
            className="bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-300 px-5 py-2.5 rounded-xl font-semibold transition-all duration-200 flex items-center gap-2"
        >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={show ? "M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" : "M15 12a3 3 0 11-6 0 3 3 0 016 0z M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"} />
            </svg>
            {show ? "Hide Reports" : "Show Reports"}
        </button>
    );

    return (
        <div className="space-y-6 animate-fade-in-up">
            <Header 
                title="Daily Reports" 
                subtitle="Generate and manage daily parking reports"
                icon="📊"
                actions={headerActions}
            />

            {/* Report Generator */}
            <div className="bg-gradient-to-br from-[#16A34A] to-[#15803D] rounded-2xl p-6 shadow-xl text-white">
                <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                    <span className="text-2xl">📅</span>
                    Generate New Report
                </h2>
                <div className="flex flex-col md:flex-row gap-4">
                    <div className="flex-1">
                        <label className="block text-sm font-medium mb-2">Select Date</label>
                        <input
                            type="date"
                            className="w-full px-4 py-3 rounded-xl text-gray-800 focus:outline-none focus:ring-2 focus:ring-white/50"
                            onChange={(e) => setDate(e.target.value)}
                        />
                    </div>
                    <div className="flex items-end">
                        <button
                            onClick={handleGenerate}
                            disabled={loading}
                            className="bg-white text-[#16A34A] px-6 py-3 rounded-xl font-semibold hover:shadow-lg hover:scale-105 transition-all duration-300 disabled:opacity-50 flex items-center gap-2 w-full md:w-auto justify-center"
                        >
                            {loading ? (
                                <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-[#16A34A]"></div>
                            ) : (
                                <>
                                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                                    </svg>
                                    Generate Report
                                </>
                            )}
                        </button>
                    </div>
                </div>
            </div>

            {/* Reports List */}
            {show && (
                <div className="space-y-6">
                    {loading && reports.length === 0 ? (
                        <div className="flex justify-center items-center h-64">
                            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[#16A34A]"></div>
                        </div>
                    ) : reports.length === 0 ? (
                        <div className="text-center py-12 bg-gray-50 dark:bg-gray-800/50 rounded-2xl">
                            <div className="text-6xl mb-4">📊</div>
                            <p className="text-gray-500 dark:text-gray-400 text-lg">No reports available</p>
                            <p className="text-gray-400 dark:text-gray-500">Generate your first report using the form above</p>
                        </div>
                    ) : (
                        reports.map((r, index) => (
                            <div
                                key={r._id}
                                className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl overflow-hidden hover:shadow-2xl transition-all duration-300 animate-fade-in-up"
                                style={{ animationDelay: `${index * 0.1}s` }}
                            >
                                <div className="bg-gradient-to-r from-[#16A34A] to-[#15803D] p-4 text-white">
                                    <div className="flex justify-between items-center flex-wrap gap-3">
                                        <div className="flex items-center gap-3">
                                            <span className="text-2xl">📅</span>
                                            <h3 className="text-xl font-bold">{r.date}</h3>
                                            <span className="bg-white/20 px-2 py-1 rounded text-sm">
                                                {r.records.length} records
                                            </span>
                                        </div>
                                        <div className="flex gap-2 flex-wrap">
                                            <button
                                                onClick={() => copyReport(r)}
                                                className="bg-white/20 hover:bg-white/30 px-3 py-1.5 rounded-lg transition-all duration-300 flex items-center gap-2 text-sm"
                                            >
                                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
                                                </svg>
                                                Copy
                                            </button>
                                            <button
                                                onClick={() => downloadPDF(r)}
                                                className="bg-white/20 hover:bg-white/30 px-3 py-1.5 rounded-lg transition-all duration-300 flex items-center gap-2 text-sm"
                                            >
                                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                                </svg>
                                                PDF
                                            </button>
                                            <button
                                                onClick={() => downloadReport(r)}
                                                className="bg-white/20 hover:bg-white/30 px-3 py-1.5 rounded-lg transition-all duration-300 flex items-center gap-2 text-sm"
                                            >
                                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                                                </svg>
                                                TXT
                                            </button>
                                            <button
                                                onClick={() => handleDelete(r._id)}
                                                className="bg-red-500/20 hover:bg-red-500/30 px-3 py-1.5 rounded-lg transition-all duration-300 flex items-center gap-2 text-sm"
                                            >
                                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                </svg>
                                                Delete
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                
                                <div className="overflow-x-auto">
                                    <table className="w-full">
                                        <thead className="bg-gray-50 dark:bg-gray-700/50">
                                            <tr>
                                                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600 dark:text-gray-300">Plate</th>
                                                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600 dark:text-gray-300">Entry</th>
                                                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600 dark:text-gray-300">Exit</th>
                                                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600 dark:text-gray-300">Duration</th>
                                                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600 dark:text-gray-300">Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {r.records.map((rec, i) => (
                                                <tr key={i} className="border-b border-gray-100 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors">
                                                    <td className="px-4 py-3 font-medium text-gray-900 dark:text-white">{rec.plateNumber}</td>
                                                    <td className="px-4 py-3 text-sm text-gray-600 dark:text-gray-400">{rec.entryTime}</td>
                                                    <td className="px-4 py-3 text-sm text-gray-600 dark:text-gray-400">{rec.exitTime}</td>
                                                    <td className="px-4 py-3 text-gray-700 dark:text-gray-300">{rec.duration}h</td>
                                                    <td className="px-4 py-3 font-semibold text-[#16A34A]">{rec.amountPaid} RWF</td>
                                                </tr>
                                            ))}
                                        </tbody>
                                        <tfoot className="bg-gray-50 dark:bg-gray-700/50">
                                            <tr>
                                                <td colSpan="4" className="px-4 py-3 text-right font-bold text-gray-900 dark:text-white">Total:</td>
                                                <td className="px-4 py-3 font-bold text-[#16A34A] text-lg">{r.total} RWF</td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        ))
                    )}
                </div>
            )}
        </div>
    );
}