import { useEffect, useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
    getPendingPayments,
    createPayment,
    getPayments,
    deletePayment
} from "../api/api";

export default function Payments() {
    const [pendingRecords, setPendingRecords] = useState([]);
    const [payments, setPayments] = useState([]);
    const [selectedRecord, setSelectedRecord] = useState(null);
    const [showHidden, setShowHidden] = useState(false);
    const [loading, setLoading] = useState(false);

    const loadData = async () => {
        setLoading(true);
        try {
            const [pendingRes, paymentRes] = await Promise.all([
                getPendingPayments(),
                getPayments()
            ]);
            setPendingRecords(pendingRes.records || []);
            setPayments(paymentRes.payments || []);
        } catch (err) {
            console.log(err);
        }
        setLoading(false);
    };

    useEffect(() => {
        loadData();
    }, []);

    const handleSelectRecord = (e) => {
        const recordId = e.target.value;
        const found = pendingRecords.find(r => r._id === recordId);
        setSelectedRecord(found);
    };

    const handlePayment = async () => {
        if (!selectedRecord) {
            showNotification("Please select a parking record", "error");
            return;
        }

        setLoading(true);
        try {
            await createPayment({ recordId: selectedRecord._id });
            showNotification("Payment completed successfully!", "success");
            setSelectedRecord(null);
            await loadData();
        } catch (err) {
            showNotification(err.message || "Payment failed", "error");
        }
        setLoading(false);
    };

    const downloadBill = (payment) => {
        const doc = new jsPDF();
        
        // Add header with gradient effect
        doc.setFillColor(147, 51, 234);
        doc.rect(0, 0, 210, 40, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.text("PSSMS PARKING BILL", 20, 25);
        
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);
        doc.text(`Bill Number: ${payment.billNumber}`, 20, 55);
        
        autoTable(doc, {
            startY: 65,
            theme: 'striped',
            head: [['Detail', 'Information']],
            body: [
                ["Plate Number", payment.recordId?.carId?.plateNumber],
                ["Driver Name", payment.recordId?.carId?.driverName],
                ["Parking Slot", payment.recordId?.slotId?.slotNumber],
                ["Entry Time", new Date(payment.recordId?.entryTime).toLocaleString()],
                ["Exit Time", new Date(payment.recordId?.exitTime).toLocaleString()],
                ["Duration", `${payment.recordId?.duration} hours`],
                ["Amount Paid", `${payment.amount} RWF`],
                ["Payment Date", new Date(payment.paymentDate).toLocaleString()],
                ["Generated By", payment.generatedBy]
            ],
            headStyles: { fillColor: [147, 51, 234] }
        });
        
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text("Thank you for using PSSMS Parking System", 20, doc.lastAutoTable.finalY + 20);
        doc.save(`${payment.billNumber}.pdf`);
    };

    const handleDelete = async (id) => {
        if (!window.confirm("Are you sure you want to delete this bill?")) return;
        
        setLoading(true);
        try {
            await deletePayment(id);
            showNotification("Bill deleted successfully", "success");
            await loadData();
        } catch (err) {
            showNotification(err.message || "Delete failed", "error");
        }
        setLoading(false);
    };

    const showNotification = (message, type) => {
        const notification = document.createElement('div');
        notification.className = `fixed top-4 right-4 z-50 px-6 py-3 rounded-xl shadow-2xl animate-slide-in flex items-center gap-2 ${
            type === 'success' ? 'bg-gradient-to-r from-green-500 to-emerald-600' : 'bg-gradient-to-r from-red-500 to-pink-600'
        } text-white`;
        notification.innerHTML = `
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="${
                    type === 'success' ? 'M5 13l4 4L19 7' : 'M6 18L18 6M6 6l12 12'
                }"></path>
            </svg>
            <span>${message}</span>
        `;
        document.body.appendChild(notification);
        setTimeout(() => notification.remove(), 3000);
    };

    const calculateAmount = (duration) => {
        return duration * 500;
    };

    return (
        <div className="space-y-6 animate-fade-in-up">
            {/* Header */}
            <div>
                <h1 className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
                    Payments & Bills
                </h1>
                <p className="text-gray-500 mt-1">Manage payments and generate parking bills</p>
            </div>

            {/* Payment Section */}
            <div className="bg-gradient-to-br from-purple-50 to-pink-50 rounded-2xl p-6 shadow-lg">
                <h2 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
                    <span className="text-2xl">💰</span>
                    Generate Payment Bill
                </h2>
                <div className="space-y-4">
                    <select
                        onChange={handleSelectRecord}
                        value={selectedRecord?._id || ""}
                        className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all duration-300"
                    >
                        <option value="">Select Completed Parking Record</option>
                        {pendingRecords.map((record) => (
                            <option key={record._id} value={record._id}>
                                {record.carId?.plateNumber} - {record.slotId?.slotNumber} - {record.duration} hrs
                            </option>
                        ))}
                    </select>

                    {selectedRecord && (
                        <div className="bg-white rounded-xl p-6 border-2 border-purple-200 animate-fade-in-up">
                            <h3 className="text-lg font-bold text-gray-800 mb-4 flex items-center gap-2">
                                <span className="text-2xl">🧾</span>
                                Bill Preview
                            </h3>
                            <div className="space-y-3">
                                <div className="flex justify-between items-center py-2 border-b border-gray-100">
                                    <span className="text-gray-600">Plate Number:</span>
                                    <span className="font-semibold">{selectedRecord.carId?.plateNumber}</span>
                                </div>
                                <div className="flex justify-between items-center py-2 border-b border-gray-100">
                                    <span className="text-gray-600">Driver Name:</span>
                                    <span className="font-semibold">{selectedRecord.carId?.driverName}</span>
                                </div>
                                <div className="flex justify-between items-center py-2 border-b border-gray-100">
                                    <span className="text-gray-600">Parking Slot:</span>
                                    <span className="font-semibold">{selectedRecord.slotId?.slotNumber}</span>
                                </div>
                                <div className="flex justify-between items-center py-2 border-b border-gray-100">
                                    <span className="text-gray-600">Entry Time:</span>
                                    <span className="font-semibold">{new Date(selectedRecord.entryTime).toLocaleString()}</span>
                                </div>
                                <div className="flex justify-between items-center py-2 border-b border-gray-100">
                                    <span className="text-gray-600">Exit Time:</span>
                                    <span className="font-semibold">{new Date(selectedRecord.exitTime).toLocaleString()}</span>
                                </div>
                                <div className="flex justify-between items-center py-2 border-b border-gray-100">
                                    <span className="text-gray-600">Duration:</span>
                                    <span className="font-semibold">{selectedRecord.duration} hours</span>
                                </div>
                                <div className="flex justify-between items-center py-3 bg-gradient-to-r from-purple-50 to-pink-50 rounded-lg px-4 -mx-2">
                                    <span className="text-lg font-bold text-gray-800">Amount:</span>
                                    <span className="text-2xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
                                        {calculateAmount(selectedRecord.duration)} RWF
                                    </span>
                                </div>
                            </div>
                            <button
                                onClick={handlePayment}
                                disabled={loading}
                                className="mt-6 w-full bg-gradient-to-r from-green-500 to-emerald-600 text-white px-6 py-3 rounded-xl font-semibold hover:shadow-lg hover:scale-105 transition-all duration-300 disabled:opacity-50 flex items-center justify-center gap-2"
                            >
                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                </svg>
                                Confirm Payment
                            </button>
                        </div>
                    )}
                </div>
            </div>

            {/* Payment History */}
            <div className="bg-white rounded-2xl shadow-xl p-6">
                <div className="flex justify-between items-center mb-6 flex-wrap gap-3">
                    <h2 className="text-2xl font-bold text-gray-800 flex items-center gap-2">
                        <span className="text-2xl">📋</span>
                        Saved Bills
                    </h2>
                    <button
                        onClick={() => setShowHidden(!showHidden)}
                        className={`px-6 py-2 rounded-xl font-semibold transition-all duration-300 flex items-center gap-2 ${
                            showHidden 
                                ? "bg-gradient-to-r from-green-500 to-emerald-600 text-white" 
                                : "bg-gradient-to-r from-gray-700 to-gray-800 text-white"
                        }`}
                    >
                        {showHidden ? (
                            <>
                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                </svg>
                                Show Visible Bills
                            </>
                        ) : (
                            <>
                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
                                </svg>
                                Hide Bills
                            </>
                        )}
                    </button>
                </div>

                <div className="mb-4">
                    {showHidden ? (
                        <p className="text-red-600 font-medium">Bills are currently hidden</p>
                    ) : (
                        <p className="text-green-600 font-medium">Bills are currently visible</p>
                    )}
                </div>

                {!showHidden && (
                    <div className="space-y-4">
                        {loading && payments.length === 0 ? (
                            <div className="flex justify-center items-center h-64">
                                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-500"></div>
                            </div>
                        ) : payments.length === 0 ? (
                            <div className="text-center py-12 bg-gray-50 rounded-2xl">
                                <div className="text-6xl mb-4">💳</div>
                                <p className="text-gray-500 text-lg">No bills available</p>
                            </div>
                        ) : (
                            payments.map((payment, index) => (
                                <div
                                    key={payment._id}
                                    className="bg-gradient-to-r from-gray-50 to-white rounded-xl p-6 shadow-md hover:shadow-xl transition-all duration-300 animate-fade-in-up border border-gray-100"
                                    style={{ animationDelay: `${index * 0.05}s` }}
                                >
                                    <div className="flex justify-between items-start mb-4 flex-wrap gap-2">
                                        <div>
                                            <div className="flex items-center gap-2 mb-1">
                                                <span className="text-2xl">🧾</span>
                                                <h3 className="font-bold text-lg text-gray-800">{payment.billNumber}</h3>
                                            </div>
                                            <span className="bg-green-100 text-green-700 px-3 py-1 rounded-full text-sm font-medium">
                                                Saved Bill
                                            </span>
                                        </div>
                                        <div className="flex gap-2">
                                            <button
                                                onClick={() => downloadBill(payment)}
                                                className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-lg transition-all duration-300 flex items-center gap-2"
                                            >
                                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                                </svg>
                                                Download PDF
                                            </button>
                                            <button
                                                onClick={() => handleDelete(payment._id)}
                                                className="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-lg transition-all duration-300 flex items-center gap-2"
                                            >
                                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                </svg>
                                                Delete
                                            </button>
                                        </div>
                                    </div>
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                                        <div className="flex items-center gap-2">
                                            <span className="text-xl">🚗</span>
                                            <div>
                                                <p className="text-xs text-gray-500">Plate Number</p>
                                                <p className="font-semibold">{payment.recordId?.carId?.plateNumber}</p>
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-2">
                                            <span className="text-xl">🅿️</span>
                                            <div>
                                                <p className="text-xs text-gray-500">Slot</p>
                                                <p className="font-semibold">{payment.recordId?.slotId?.slotNumber}</p>
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-2">
                                            <span className="text-xl">⏱️</span>
                                            <div>
                                                <p className="text-xs text-gray-500">Duration</p>
                                                <p className="font-semibold">{payment.recordId?.duration} hrs</p>
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-2">
                                            <span className="text-xl">💰</span>
                                            <div>
                                                <p className="text-xs text-gray-500">Amount</p>
                                                <p className="font-bold text-green-600">{payment.amount} RWF</p>
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-2 md:col-span-2">
                                            <span className="text-xl">📅</span>
                                            <div>
                                                <p className="text-xs text-gray-500">Payment Date</p>
                                                <p className="font-semibold text-sm">{new Date(payment.paymentDate).toLocaleString()}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            ))
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}