import { useEffect, useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
    getPendingPayments,
    createPayment,
    getPayments,
    deletePayment
} from "../api/api";
import Header from "../components/Header";

export default function Payments() {
    const [pendingRecords, setPendingRecords] = useState([]);
    const [payments, setPayments] = useState([]);
    const [selectedRecord, setSelectedRecord] = useState(null);
    const [showHidden, setShowHidden] = useState(false);
    const [loading, setLoading] = useState(false);

    const loadData = async () => {
        setLoading(true);
        try {
            const [pendingRes, paymentRes] = await Promise.all([
                getPendingPayments(),
                getPayments()
            ]);
            setPendingRecords(pendingRes.records || []);
            setPayments(paymentRes.payments || []);
        } catch (err) {
            console.log(err);
        }
        setLoading(false);
    };

    useEffect(() => {
        loadData();
    }, []);

    const handleSelectRecord = (e) => {
        const recordId = e.target.value;
        const found = pendingRecords.find(r => r._id === recordId);
        setSelectedRecord(found);
    };

    const handlePayment = async () => {
        if (!selectedRecord) {
            showNotification("Please select a parking record", "error");
            return;
        }

        setLoading(true);
        try {
            await createPayment({ recordId: selectedRecord._id });
            showNotification("Payment completed successfully!", "success");
            setSelectedRecord(null);
            await loadData();
        } catch (err) {
            showNotification(err.message || "Payment failed", "error");
        }
        setLoading(false);
    };

    const downloadBill = (payment) => {
        const doc = new jsPDF();
        
        // Eco Smart Parking Header
        doc.setFillColor(22, 163, 74);
        doc.rect(0, 0, 210, 45, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.text("Parking Space Sales Management System", 20, 25);
        doc.setFontSize(12);
        doc.text("Payment Receipt", 20, 35);
        
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);
        doc.text(`Bill Number: ${payment.billNumber}`, 20, 60);
        doc.text(`Date: ${new Date(payment.paymentDate).toLocaleString()}`, 20, 70);
        
        autoTable(doc, {
            startY: 80,
            theme: 'striped',
            head: [['Detail', 'Information']],
            body: [
                ["Plate Number", payment.recordId?.carId?.plateNumber],
                ["Driver Name", payment.recordId?.carId?.driverName],
                ["Parking Slot", payment.recordId?.slotId?.slotNumber],
                ["Entry Time", new Date(payment.recordId?.entryTime).toLocaleString()],
                ["Exit Time", new Date(payment.recordId?.exitTime).toLocaleString()],
                ["Duration", `${payment.recordId?.duration} hours`],
                ["Amount Paid", `${payment.amount} RWF`],
                ["Payment Method", "Cash / Mobile Money"],
                ["Generated By", payment.generatedBy || "System"]
            ],
            headStyles: { fillColor: [22, 163, 74] }
        });
        
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text("Thank you for choosing Parking Space Sales Management System!", 20, doc.lastAutoTable.finalY + 20);
        doc.text("🌿 This is a carbon-neutral facility", 20, doc.lastAutoTable.finalY + 30);
        doc.save(`${payment.billNumber}.pdf`);
        showNotification("Bill downloaded successfully!", "success");
    };

    const handleDelete = async (id) => {
        if (!window.confirm("Are you sure you want to delete this bill?")) return;
        
        setLoading(true);
        try {
            await deletePayment(id);
            showNotification("Bill deleted successfully", "success");
            await loadData();
        } catch (err) {
            showNotification(err.message || "Delete failed", "error");
        }
        setLoading(false);
    };

    const showNotification = (message, type) => {
        const notification = document.createElement('div');
        notification.className = `fixed top-20 right-4 z-50 px-6 py-3 rounded-xl shadow-2xl animate-slide-in flex items-center gap-2 ${
            type === 'success' ? 'bg-gradient-to-r from-[#16A34A] to-[#15803D]' : 'bg-gradient-to-r from-red-500 to-red-600'
        } text-white`;
        notification.innerHTML = `
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="${
                    type === 'success' ? 'M5 13l4 4L19 7' : 'M6 18L18 6M6 6l12 12'
                }"></path>
            </svg>
            <span>${message}</span>
        `;
        document.body.appendChild(notification);
        setTimeout(() => notification.remove(), 3000);
    };

    const calculateAmount = (duration) => {
        return duration * 500;
    };

    const headerActions = (
        <button
            onClick={() => setShowHidden(!showHidden)}
            className={`px-5 py-2.5 rounded-xl font-semibold transition-all duration-300 flex items-center gap-2 ${
                showHidden 
                    ? "bg-gradient-to-r from-[#16A34A] to-[#15803D] text-white" 
                    : "bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300"
            }`}
        >
            {showHidden ? (
                <>
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                    Show Bills
                </>
            ) : (
                <>
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
                    </svg>
                    Hide Bills
                </>
            )}
        </button>
    );

    return (
        <div className="space-y-6 animate-fade-in-up">
            <Header 
                title="Payments & Bills" 
                subtitle="Manage payments and generate parking bills"
                icon="💰"
                actions={headerActions}
            />

            {/* Payment Section */}
            <div className="bg-gradient-to-br from-[#16A34A]/10 to-[#15803D]/10 dark:from-[#16A34A]/20 dark:to-[#15803D]/20 rounded-2xl p-6 shadow-lg">
                <h2 className="text-xl font-bold text-gray-800 dark:text-white mb-4 flex items-center gap-2">
                    <span className="text-2xl">💳</span>
                    Generate Payment Bill
                </h2>
                <div className="space-y-4">
                    <select
                        onChange={handleSelectRecord}
                        value={selectedRecord?._id || ""}
                        className="w-full px-4 py-3 border border-gray-200 dark:border-gray-700 rounded-xl bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-[#16A34A]/40 focus:border-[#16A34A] transition-all duration-300"
                    >
                        <option value="">Select Completed Parking Record</option>
                        {pendingRecords.map((record) => (
                            <option key={record._id} value={record._id}>
                                {record.carId?.plateNumber} - Slot {record.slotId?.slotNumber} - {record.duration} hrs
                            </option>
                        ))}
                    </select>

                    {selectedRecord && (
                        <div className="bg-white dark:bg-gray-800 rounded-xl p-6 border-2 border-[#16A34A]/30 animate-fade-in-up">
                            <h3 className="text-lg font-bold text-gray-800 dark:text-white mb-4 flex items-center gap-2">
                                <span className="text-2xl">🧾</span>
                                Bill Preview
                            </h3>
                            <div className="space-y-3">
                                <div className="flex justify-between items-center py-2 border-b border-gray-100 dark:border-gray-700">
                                    <span className="text-gray-600 dark:text-gray-400">Plate Number:</span>
                                    <span className="font-semibold text-gray-900 dark:text-white">{selectedRecord.carId?.plateNumber}</span>
                                </div>
                                <div className="flex justify-between items-center py-2 border-b border-gray-100 dark:border-gray-700">
                                    <span className="text-gray-600 dark:text-gray-400">Driver Name:</span>
                                    <span className="font-semibold text-gray-900 dark:text-white">{selectedRecord.carId?.driverName}</span>
                                </div>
                                <div className="flex justify-between items-center py-2 border-b border-gray-100 dark:border-gray-700">
                                    <span className="text-gray-600 dark:text-gray-400">Parking Slot:</span>
                                    <span className="font-semibold text-gray-900 dark:text-white">{selectedRecord.slotId?.slotNumber}</span>
                                </div>
                                <div className="flex justify-between items-center py-2 border-b border-gray-100 dark:border-gray-700">
                                    <span className="text-gray-600 dark:text-gray-400">Entry Time:</span>
                                    <span className="font-semibold text-gray-900 dark:text-white">{new Date(selectedRecord.entryTime).toLocaleString()}</span>
                                </div>
                                <div className="flex justify-between items-center py-2 border-b border-gray-100 dark:border-gray-700">
                                    <span className="text-gray-600 dark:text-gray-400">Exit Time:</span>
                                    <span className="font-semibold text-gray-900 dark:text-white">{new Date(selectedRecord.exitTime).toLocaleString()}</span>
                                </div>
                                <div className="flex justify-between items-center py-2 border-b border-gray-100 dark:border-gray-700">
                                    <span className="text-gray-600 dark:text-gray-400">Duration:</span>
                                    <span className="font-semibold text-gray-900 dark:text-white">{selectedRecord.duration} hours</span>
                                </div>
                                <div className="flex justify-between items-center py-3 bg-gradient-to-r from-[#16A34A]/10 to-[#15803D]/10 rounded-lg px-4 -mx-2">
                                    <span className="text-lg font-bold text-gray-800 dark:text-white">Amount:</span>
                                    <span className="text-2xl font-bold text-[#16A34A]">
                                        {calculateAmount(selectedRecord.duration)} RWF
                                    </span>
                                </div>
                            </div>
                            <button
                                onClick={handlePayment}
                                disabled={loading}
                                className="mt-6 w-full bg-gradient-to-r from-[#16A34A] to-[#15803D] text-white px-6 py-3 rounded-xl font-semibold hover:shadow-lg hover:scale-105 transition-all duration-300 disabled:opacity-50 flex items-center justify-center gap-2"
                            >
                                {loading ? (
                                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                                ) : (
                                    <>
                                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                        </svg>
                                        Confirm Payment
                                    </>
                                )}
                            </button>
                        </div>
                    )}
                    
                    {pendingRecords.length === 0 && (
                        <div className="text-center py-8 bg-gray-50 dark:bg-gray-800/50 rounded-xl">
                            <p className="text-gray-500 dark:text-gray-400">No pending payments available</p>
                        </div>
                    )}
                </div>
            </div>

            {/* Payment History */}
            {!showHidden && (
                <div className="space-y-4">
                    <h2 className="text-xl font-bold text-gray-800 dark:text-white flex items-center gap-2">
                        <span className="text-2xl">📋</span>
                        Saved Bills ({payments.length})
                    </h2>
                    
                    {loading && payments.length === 0 ? (
                        <div className="flex justify-center items-center h-64">
                            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[#16A34A]"></div>
                        </div>
                    ) : payments.length === 0 ? (
                        <div className="text-center py-12 bg-gray-50 dark:bg-gray-800/50 rounded-2xl">
                            <div className="text-6xl mb-4">💳</div>
                            <p className="text-gray-500 dark:text-gray-400 text-lg">No bills available</p>
                            <p className="text-gray-400 dark:text-gray-500">Generate your first bill using the form above</p>
                        </div>
                    ) : (
                        payments.map((payment, index) => (
                            <div
                                key={payment._id}
                                className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-md hover:shadow-xl transition-all duration-300 animate-fade-in-up border border-gray-100 dark:border-gray-700"
                                style={{ animationDelay: `${index * 0.05}s` }}
                            >
                                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-4">
                                    <div>
                                        <div className="flex items-center gap-2 mb-1">
                                            <span className="text-2xl">🧾</span>
                                            <h3 className="font-bold text-lg text-gray-800 dark:text-white">{payment.billNumber}</h3>
                                        </div>
                                        <span className="bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 px-3 py-1 rounded-full text-sm font-medium">
                                            Paid
                                        </span>
                                    </div>
                                    <div className="flex gap-2">
                                        <button
                                            onClick={() => downloadBill(payment)}
                                            className="bg-gradient-to-r from-[#16A34A] to-[#15803D] hover:from-[#15803D] hover:to-[#16A34A] text-white px-4 py-2 rounded-lg transition-all duration-300 flex items-center gap-2"
                                        >
                                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                            </svg>
                                            PDF
                                        </button>
                                        <button
                                            onClick={() => handleDelete(payment._id)}
                                            className="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-lg transition-all duration-300 flex items-center gap-2"
                                        >
                                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                            Delete
                                        </button>
                                    </div>
                                </div>
                                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                                    <div>
                                        <p className="text-xs text-gray-500 dark:text-gray-400">Plate Number</p>
                                        <p className="font-semibold text-gray-900 dark:text-white">{payment.recordId?.carId?.plateNumber}</p>
                                    </div>
                                    <div>
                                        <p className="text-xs text-gray-500 dark:text-gray-400">Slot</p>
                                        <p className="font-semibold text-gray-900 dark:text-white">{payment.recordId?.slotId?.slotNumber}</p>
                                    </div>
                                    <div>
                                        <p className="text-xs text-gray-500 dark:text-gray-400">Duration</p>
                                        <p className="font-semibold text-gray-900 dark:text-white">{payment.recordId?.duration} hrs</p>
                                    </div>
                                    <div>
                                        <p className="text-xs text-gray-500 dark:text-gray-400">Amount</p>
                                        <p className="font-bold text-[#16A34A] text-lg">{payment.amount} RWF</p>
                                    </div>
                                </div>
                                <div className="mt-3 pt-3 border-t border-gray-100 dark:border-gray-700">
                                    <p className="text-xs text-gray-500 dark:text-gray-400">Payment Date</p>
                                    <p className="text-sm text-gray-700 dark:text-gray-300">{new Date(payment.paymentDate).toLocaleString()}</p>
                                </div>
                            </div>
                        ))
                    )}
                </div>
            )}
        </div>
    );
}